# 应用配置
config:
  url: jdbc:mysql://localhost:3306/${config.database}?allowMutiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true
  user: root
  pwd: '@WPSasdf123456'
  class-name: com.mysql.cj.jdbc.Driver
  path: top.resty.spboot
  upload-path: /home/dist/upload/
# Spring Boot 配置
spring:
  datasource:
    url: ${config.url}
    username: ${config.user}
    password: ${config.pwd}
    driver-class-name: ${config.class-name}
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
      max-lifetime: 12
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# bean-searcher 配置

# logging 配置
logging:
  level:
    root: info
    top.resty.spboot.mapper: debug
    cn.zhxu.bs: debug

# ssl 配置
server:
  port: 8080 # https 端口号
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.jks
#    key-store-password: restyhap
#    key-store-type: JKS
